### PR TITLE
Add a basic forward kinematics example using the Finger

### PR DESCRIPTION
**Pull request by luator**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description
Add a basic forward kinematics example using the Finger

## How I Tested
By running it.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by luator** [comment]
@shrutij01 FYI

**Comment by shrutij01** [comment]
Thank you so much @luator

**Comment by luator** [comment]
@mwuethri Can you take a look at this?

**Comment by mwuethri** [comment]
thanks, that's very useful! i am not super familiar with pinocchio, so maybe @MaximilienNaveau  could have a quick look?

minor point: justin carpentier told me that pinocchio supports also using np arrays instead of matrices, i think it can be set somewhere when you set up pinocchio. this would remove the need for conversion. @MaximilienNaveau do you know how to do this?

**Comment by luator** [comment]
Closed in favour of https://github.com/open-dynamic-robot-initiative/robot_fingers/pull/2

**Pull request closed without merging**
