### PR TITLE
Add missing dependency on mpi_cpp_tools

### PR DESCRIPTION
**Pull request by luator**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

The mpi_cpp_tools is used in this package but was not properly specified as dependency.

## How I Tested

Compiled.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
it was not compiling before? weird...

**Comment by luator** [comment]
It was provided as a dependency by another package but I removed it there as it was unused.
Will this need a corresponding treep update?  I'll check.

**Comment by MaximilienNaveau** [comment]
Do you know where we use it?

**Comment by luator** [comment]
All good, it's already listed for the `BLMC_ROBOTS` project, so nothing to change for treep.

It is used in `n_joint_blmc_robot_driver.hpp` which is a header-only file.  So even if the dependency was not provided by an other package, you would not see the build error unless you actually use that file somewhere.

**Comment by MaximilienNaveau** [comment]
Could we get rid of this dependency?

**Comment by luator** [comment]
Seems like the only thing used is the `clamp` function.  So could be removed if needed but we would need to duplicate this function.  Is there a problem with having it?

**Comment by MaximilienNaveau** [comment]
I do not like the word "tools" it is like you did not know what to put in it so you call it tool... I do not think it is a healthy way of naming and sorting thing. (I know I have a dg_tools package but things are getting slowly removed from there as well).
So I would rather duplicate the clamp function if this is the only thing we pull out from this package.

**Comment by luator** [comment]
I think it's good to have a collection of generic math functions for things like this that may be needed in very different contexts (another example would be a `sign` function).  As the purpose of these packages is to be generic, I think there is often simply no better name than "tools" or "utils".

I agree, though, that the current package is a bit too unfocused.  What do you think about moving the math-part out of this into a more focused package called `math_utils` or similar?

**Comment by MaximilienNaveau** [comment]
It is gonna be harsh but honestly there is nothing in mpi_cpp_tools that I would re-use.
The clamping function is as well known as a PD controller, and everybody has one implemented somewhere.
The linear dynamic system does not belong here but in an optimal control package. Or even "linear_dynamics" one.
And furthermore the package is not updated so often either... So I would rather not depend on it if I can...

**Comment by luator** [comment]
I checked what is actually in this package and where it is used.  While I still believe in the general usefulness of utils packages (it is not about how well known something is but about not reinventing the wheel), I agree now that we could get rid of mpi_cpp_tools.

It seems that at least within the BLMC_EI project the only thing ever used of this package is the clamp function and this is also only used in blmc_robots, nowhere else.  In this case it really doesn't make a lot of sense to keep it in a separate package.  I'll make a PR removing it.

**Comment by MaximilienNaveau** [comment]
Thank you very much. In principle I think I agree with you. Even though right now I did not really find the good way of implementing this.

**Comment by luator** [comment]
#74

**Pull request merged**
