### PR TITLE
Remove BlmcJointModule(s) and NJointBlmcRobotDriver

### PR DESCRIPTION
**Pull request by luator**
## Description

- `BlmcJointModule(s)` is moved to `blmc_drivers`
- `NJointBlmcRobotDriver` is moved to `robot_fingers`

## How I Tested

Unit tests pass. Also tested some demos on the TriFinger robot.

## Do not merge before

[//]: # "Link other open pull request here that need to be merged first."
[//]: # "Remove this section if it does not apply."

- Related PRs on blmc_drivers and robot_fingers are ready.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by luator** [comment]
@MaximilienNaveau I now tested on the TriFinger robot and everything worked normally.  Could you maybe do some quick test on your robots, to make sure it doesn't break anything there?

**Review by MaximilienNaveau — COMMENTED** [review]
Sounds good to me!

**Review by MaximilienNaveau — APPROVED** [review]
good

**Comment by luator** [comment]
@MaximilienNaveau Just to make sure: Can I merge already or do you still want to test?

**Comment by MaximilienNaveau** [comment]
I would say go ahead, worst case we can revert this PR through github.

**Pull request merged**
